# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed91299a9518b00a1b35eec05d39aa551472df85caf58aed3ca08be2bc1ef3a6b3c9a4be9e0baa2d75c96d9edec5624b1bda9d30af3e4c652e5920d66fa4c46f

test:
  secret_key_base: 2b7a2aa84f230710f18e95b4474ee3d6868f4b878e06e7ad328d361e531dd3c010bef2dad52377f6f921f848539ffa1407e2760f6940660b48a57c128d82bcb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
